apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: basic-ocp-demo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/FreedomBen/basic-ocp-demo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: basic-ocp-demo-image
spec:
  type: image
  params:
  - name: url
    value: quay.io/freedomben/basic-ocp-demo:latest
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: basic-ocp-demo-build-pipeline
spec:
  resources:
  - name: basic-ocp-demo
    type: git
  - name: basic-ocp-demo-image
    type: image
  - name: basic-ocp-demo-git
  params:
  - name: imageTag
    type: string
    default: latest
    description: Tag for the built image
  tasks:
  - name: build-and-push
    taskRef:
      name: build-from-dockerfile
    # runAfter:
    #   - imageTag
    params:
      - name: DOCKERFILE_PATH
        value: "./Dockerfile"
      - name: IMAGE_TAG
        value: "$(params.imageTag)"
    resources:
      inputs:
      - name: source
        resource: basic-ocp-demo-git
      outputs:
      - name: image
        resource: basic-ocp-demo-image
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-from-dockerfile
spec:
  inputs:
    resources:
    - name: source
      type: git
    - name: basic-ocp-demo-git
      type: git
    params:
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
      default: "true"
    - name: DOCKERFILE_PATH
      description: Path to the Dockerfile file
      default: ./Dockerfile
    - name: IMAGE_TAG
      description: Tag for the built image
      default: latest
  outputs:
    resources:
    - name: image
      type: image

  steps:
  - name: build
    image: quay.io/buildah/stable
    workingdir: /workspace/source
    command: ['buildah', 'bud', '--tls-verify=$(inputs.params.TLSVERIFY)', '--layers', '-f', '$(inputs.params.DOCKERFILE_PATH)', '-t', '$(outputs.resources.image.url):$(inputs.params.IMAGE_TAG)', '.']
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true

  - name: push
    image: quay.io/buildah/stable
    command: ['buildah', 'push', '--tls-verify=$(inputs.params.TLSVERIFY)', '$(outputs.resources.image.url):$(inputs.params.IMAGE_TAG)', 'docker://$(outputs.resources.image.url):$(inputs.params.IMAGE_TAG)']
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true

  volumes:
  - name: varlibcontainers
    emptyDir: {}